### ISSUE TITLE
Success/confirmation messages not shown after uploading measurements

### ISSUE THREAD

**Issue by Florisklooster** [ArtesiaWater/field_form#17]
When trying to send measurements, a loading display is shown which does not dissapear unless the app is restarted or by choosing 'change ftp map' and subsequently choose 'no' when it says that there are not-sendend measurments, do you first want to upload them?

There is no success/confirmation message that the uploading was successfull, even if it did actually upload the measurements.

It seems that until now, all measurements were uploaded nontheless to the ftp server. But not knowing for sure if the measurements are actuallly uploaded to the ftp map or having to check all the time is not quite handy. 

Some oddities that might help finding the issue: First one college encountered this problem, and the other had no problems with the app, curently another college (that did not have this problem untill recently) has this problem as well, while I do not have the problem (all using version 1.1.1).

**Comment by Florisklooster** [comment]
Another thing, that is not so much of a problem but might be a lead to the problem. Is that a colleague successfully sent measurements to the FTP server (but no succes-message was shown), and two minutes later sent the same measurements (I am not sure if a succes-message was shown, but I don't think so). 
Of course if there are no new measurements this should not occur (at least not with the settings we apply), if there is good communication between the app and the FTP server.

**Comment by Florisklooster** [comment]
Another problem, that might be related, is that approximately 5% of the photos that were taken are not on the FTP server, although the name of the photo is in the measurements*.csv

**Comment by Florisklooster** [comment]
Another issue (might be related) that occasionally occurs is the unexpected clearing of fields that were previously filled in (the particularl issue I heard recently was clearing of fields after taking a picture)

**Comment by rubencalje** [comment]
Sometimes a break in connection with the ftp-server while uploading a file (or changing the active directory) resulted in an uncaught error, which caused the loading display to stay active. This is a bug, and should be fixed in the commit 482102f. 

I think in the scenario described above, this caused the following problem:
- first, the measurements-file was uploaded to the ftp-sever.
- during the upload of one of the photos the connection was lost, the synchronization-process was aborted, and the loading screen remained active. This step results in the names of photos in the measurement-files on the ftp-server, while the photos are not on the ftp-server.
- in a new synchronization attempt, the same measurements were uploaded in another measurement-file, causing double measurements on the ftp-sever. The app then attempts to upload the missing photos again. 

Commit 482102f should help decrease the chance of these problems happening, but double measurements will still happen when the uploading of one of the photo's fails. Only when the app succeeds in sending all photos to the ftp-server, the measurements and photos will not be sent to the ftp-server anymore in following synchronization-attempts.

> Another issue (might be related) that occasionally occurs is the unexpected clearing of fields that were previously filled in (the particularl issue I heard recently was clearing of fields after taking a picture)

I have not encountered the clearing of fields myself, also in some tests where I rotate my screen or take a picture. If it happens again, please describe what happened in a new issue.
